language: python

cache: pip

python:
  - "2.7"

addons:
  apt:
    packages:
    - swig

script:
  - pip install numpy pillow pytest
  - python setup.py build_ext
  - python setup.py install
  - py.test
  - heman-gen
